# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://hacked-jekyll.netlify.app

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Tom's Website
  description:
    - Hello!
    - This is a holding page
    - Until I make somehting nicer
    - Thanks for visiting
 # cv: assets/cv.pdf
 # address:
 #   - University of Jekyll
 #   - Department of Themes
 #   - 123 Main St, Anytown, USA
 # contact:
 #   office: Foobar Hall 1.23
 #   phone: +1 234 567 890
 #   email: username@domain.com
 # demo: https://hacked-jekyll.netlify.app
#  source: https://github.com/piazzai/hacked-jekyll
  profiles:
#    facebook: https://www.facebook.com
#    twitter: https://twitter.com
#    instagram: https://www.instagram.com
    linkedin: https://www.linkedin.com/in/tomredd
#    stackoverflow: https://stackoverflow.com
    github: https://github.com/tomredd

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
